### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [luratic/MailerLite#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The [documentation url](https://www.luratic.com/posts/templates/tags/mailerlite/) mentioned in the manifest file is invalid. Please provide valid url.
![Screenshot 2020-11-10 at 4 04 52 PM](https://user-images.githubusercontent.com/53495700/98748551-ca292180-236e-11eb-8129-33dcc1e00889.png)

**Comment by luratic-devs** [comment]
Hi, 

The problem is solved.
In the next few days, we will update documentation. 

Many Thanks!
